pipeline {
    agent any

    environment {
        APP_NAME = 'llm-log-analyzer'
        CONTAINER_NAME = 'llm-log-analyzer-container'
        IMAGE_NAME = 'llm-log-analyzer'
        API_URL = 'http://host.docker.internal:8000/analyze'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME} .'
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                    docker rm -f ${CONTAINER_NAME} || true
                    docker run -d --name ${CONTAINER_NAME} \
                      -p 8000:8000 \
                      -e OLLAMA_HOST=http://host.docker.internal:11434 \
                      -e OLLAMA_MODEL=gemma3 \
                      ${IMAGE_NAME}
                '''
            }
        }

        stage('Wait for App') {
    steps {
        sh 'sleep 15'
    }
}

stage('Test API') {
    steps {
        sh '''
            curl -X POST http://llm-log-analyzer-container:8000/analyze \
              -H "Content-Type: application/json" \
              -d '{"log_text":"ERROR: No module named requests"}'
        '''
    }
}
    }

    post {
        always {
            sh 'docker stop ${CONTAINER_NAME} || true'
            sh 'docker rm ${CONTAINER_NAME} || true'
        }
    }
}